name: atelier

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - jupyter=1.0.0
  - scikit-learn=1.0
  - pandas=1.3.4
  - plotly=5.3.1
  - pyarrow=5.0.0
  - ipython=7.28.0
  - pip=21.3
  - pip:
      - poetry==1.1.11
      - folium==0.12.1
      - ipykernel==6.4.2
