name: atelier

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - folium=0.12.0
  - jupyter=1.0.0
  - scikit-learn=1.0
  - pandas=1.3.4
  - plotly=5.3.1
  - poetry=1.1.11
  - pyarrow=5.0.0
  - ipykernel=6.4.1
  - ipython=7.28.0
